name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Instalar dependencias
      run: sudo apt-get update && sudo apt-get install -y \
        git make gcc g++ libncurses5-dev libssl-dev bc flex bison

    - name: Sincronizar repositorio
      run: |
        git submodule update --init --recursive
        # Si usas repo:
        # repo init -u https://android.googlesource.com/platform/manifest -b <branch>
        # repo sync

    - name: Compilar recovery
      run: |
        make clean
        make recoveryimage
