name: Makefile CI (Rápido)

on:
  workflow_dispatch:   # se ejecuta manualmente desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Instalar dependencias mínimas
      run: sudo apt-get update && sudo apt-get install -y \
        make gcc g++ libncurses5-dev libssl-dev bc flex bison

    - name: Compilar recovery
      run: |
        source build/envsetup.sh
        lunch twrp_gta9p-eng
        make recoveryimage -j$(nproc)